## 00. PyTorch Fundamentals

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,6,7])
vector

tensor([7, 6, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random Tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those randon numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3433, 0.2971, 0.4272, 0.6060],
        [0.0863, 0.9497, 0.6163, 0.8246],
        [0.2375, 0.2675, 0.5014, 0.9660]])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and Ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones

ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [ ]:
# use torch.arange()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creatin a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right divice

In [ ]:
# float 32 tensor

# dtype = torch.float16
# device = "cpu"
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # data type of tensor
                               device = None, # what device yout tensor on
                               requires_grad = False) # wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
MATA = torch.rand(size = (3,4))
MATB = torch.rand(size = (3,4))
MATA = MATA*10
MATB = MATB*10
print(MATA)
print(MATB)
print(MATA*MATB)

tensor([[9.8527, 6.8508, 0.2081, 7.7622],
        [2.9367, 6.3524, 0.9363, 7.0762],
        [6.6596, 2.6321, 8.7420, 2.4603]])
tensor([[7.7682, 7.7851, 1.2931, 2.3837],
        [9.7932, 1.4169, 9.0046, 2.0112],
        [7.1427, 2.8711, 1.7631, 4.8652]])
tensor([[76.5376, 53.3340,  0.2691, 18.5030],
        [28.7601,  9.0011,  8.4312, 14.2316],
        [47.5671,  7.5571, 15.4129, 11.9697]])
