## 00. PyTorch Fundamentals

In [1]:
!nvidia-smi

Mon Apr 29 14:51:50 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,6,7])
vector

tensor([7, 6, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random Tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those randon numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [14]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0057, 0.3993, 0.3684, 0.7240],
        [0.3856, 0.9252, 0.6536, 0.6457],
        [0.5227, 0.7710, 0.8557, 0.4765]])

In [15]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and Ones

In [16]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# create a tensor of all ones

ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [19]:
# use torch.arange()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# creatin a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

In [21]:
# float 32 tensor

# dtype = torch.float16
# device = "cpu"
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # data type of tensor
                               device = None, # what device your tensor on (eg,: "cuda")
                               requires_grad = False) # wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
a = float_16_tensor * float_32_tensor
a.dtype

torch.float32

In [25]:
MATA = torch.rand(size = (3,4))
MATB = torch.rand(size = (3,4))
MATA = MATA*10
MATB = MATB*10
print(MATA)
print(MATB)
print(MATA*MATB)

tensor([[9.1913, 0.8769, 0.8810, 0.7959],
        [5.3285, 1.7313, 6.7748, 5.8154],
        [7.2066, 0.7455, 7.5943, 8.2398]])
tensor([[6.9985, 9.7233, 2.1348, 7.9674],
        [4.8483, 7.2255, 8.9146, 6.5253],
        [5.1687, 4.0107, 2.2249, 5.8170]])
tensor([[64.3257,  8.5268,  1.8808,  6.3413],
        [25.8340, 12.5092, 60.3950, 37.9476],
        [37.2487,  2.9901, 16.8969, 47.9310]])


### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [26]:
# creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1965, 0.2028, 0.3400, 0.7451],
        [0.0655, 0.0413, 0.7099, 0.0329],
        [0.5069, 0.6578, 0.9702, 0.3942]])

In [27]:
some_tensor.size(), some_tensor.shape # both are same

(torch.Size([3, 4]), torch.Size([3, 4]))

In [28]:
# find out details about `some_tensor`
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1965, 0.2028, 0.3400, 0.7451],
        [0.0655, 0.0413, 0.7099, 0.0329],
        [0.5069, 0.6578, 0.9702, 0.3942]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [29]:
# Create a tensor and add 10 to all elements
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# multiply 10 to all elements
tensor * 10

tensor([10, 20, 30])

In [31]:
# subtract 10 from all elements
tensor - 10

tensor([-9, -8, -7])

In [32]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor,tensor)
tensor.shape

torch.Size([3])

### Matrix multiplication

Two main ways of performing multiplacation in neural network and deeplearning:

1. Element-wise Multiplication
2. Matrix multiplication (dot product) (`@` symbol)

There are two main rules that performing matrix multiplication needs to satisfy:

1. the **inner dimensions** must match
2. the resulting matrix has the shape of the **outer dimensions**

In [33]:
torch.matmul(torch.rand(3,4),torch.rand(4,8)).shape

torch.Size([3, 8])

In [34]:
torch.matmul(tensor,tensor) # 1*1 + 2*2 + 3*3

tensor(14)

In [35]:
%%time
value = 0
for i in tensor:
  value += i*i
print(value)

tensor(14)
CPU times: user 1.42 ms, sys: 85 µs, total: 1.51 ms
Wall time: 5.11 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 416 µs, sys: 683 µs, total: 1.1 ms
Wall time: 1.81 ms


tensor(14)

### one of the most common errors in deep learning: shape errors

In [37]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul

To fix our tensor shape isseues, we can munipulate the shape of one of our tensors using a `transpose`.
A `transpose` switches the axes or dimensions of a given tensor.

In [38]:
tensor_B.T
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [39]:
# Create a tensor

x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [41]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [42]:
# find the mean

# note: the torch.mean() function requires a tensor of float32 datatype to work

print(x.dtype)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

torch.int64


(tensor(46.), tensor(46.))

In [43]:
# find the sum of elements in the tensor
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## finding the positional min and max

In [44]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [45]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [46]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensirs

* reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory ans the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or sideby side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [47]:
x = torch.arange(1., 10.)
print(x, x.shape)
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [48]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [50]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

temp1 = torch.tensor([[1.],[2.],[3.],[4.],[5.],[6.]])
temp2 = torch.tensor([[4.],[5.],[6.],[7.],[8.],[9.]])
dimension = 2
print(f"temp1 = {temp1}\n temp2 = {temp2}")
stk = torch.stack((temp1, temp2),dim = dimension)
print(f"stacked at dim {dimension} = {stk}\n shape of stacked = {stk.shape}\n\n")
vstk = torch.vstack((temp1, temp2))
hstk = torch.hstack((temp1, temp2))
print(f"vertical stack = {vstk}\n horizontal stack = {hstk}\n")

temp1 = tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
 temp2 = tensor([[4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
stacked at dim 2 = tensor([[[1., 4.]],

        [[2., 5.]],

        [[3., 6.]],

        [[4., 7.]],

        [[5., 8.]],

        [[6., 9.]]])
 shape of stacked = torch.Size([6, 1, 2])


vertical stack = tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
 horizontal stack = tensor([[1., 4.],
        [2., 5.],
        [3., 6.],
        [4., 7.],
        [5., 8.],
        [6., 9.]])



In [51]:
# torch.squeeze() - removes all single dimentions from a target tensor

x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
x_squeezed = x_reshaped.squeeze()

In [53]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)

In [54]:
# torch.permute - rearranges the dimensions of a  target tensor in a specified order
x_original = torch.rand(size = (224,224,3)) # [height, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

## Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing to NumPy.

In [55]:
# create a tensor
x = torch.arange(1,10).reshape(1, 3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [56]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor
# changing np array won't effect the tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [57]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
# changing tensor won't effect the np array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

from typing_extensions import LiteralString
## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduse the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [58]:
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

# random_tensor_A[0][0] = 3
# random_tensor_B[0][0] = 3

print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [59]:
# Let's make some random but reproducible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what options to get: https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [60]:
!nvidia-smi

Mon Apr 29 14:52:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU acess with PyTorch

In [62]:
# check fro GPU acesss with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.
E.g.: run on GPU if available, else default to CPU

In [63]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [64]:
# Count number of devices
torch.cuda.device_count()1

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because, using a GPU results in faster computations

In [66]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# GTensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [67]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [69]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()

In [70]:
# To fix GPU tensor with NumPy issue, we can forst set it ot the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [71]:
tensor_on_gpu # remains unchanged

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

See Exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises