## 00. PyTorch Fundamentals

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,6,7])
vector

tensor([7, 6, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

why random Tensors?

random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those randon numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers`

In [14]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8111, 0.6505, 0.5728, 0.6437],
        [0.4404, 0.9672, 0.5998, 0.0080],
        [0.5462, 0.0856, 0.2035, 0.4876]])

In [15]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (244,244,3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and Ones

In [16]:
# create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# create a tensor of all ones

ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [19]:
# use torch.arange()
one_to_ten = torch.arange(start = 1,end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# creatin a tensor like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

In [26]:
# float 32 tensor

# dtype = torch.float16
# device = "cpu"
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # data type of tensor
                               device = None, # what device your tensor on (eg,: "cuda")
                               requires_grad = False) # wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
a = float_16_tensor * float_32_tensor
a.dtype

torch.float32

In [25]:
MATA = torch.rand(size = (3,4))
MATB = torch.rand(size = (3,4))
MATA = MATA*10
MATB = MATB*10
print(MATA)
print(MATB)
print(MATA*MATB)

tensor([[3.2912, 9.1599, 6.6045, 9.4435],
        [0.8519, 3.3291, 7.3455, 0.9082],
        [2.2478, 3.2629, 4.0008, 8.3980]])
tensor([[2.2672, 9.7960, 4.5241, 2.1621],
        [1.0554, 4.0624, 2.1315, 4.3366],
        [8.1157, 8.8064, 6.9629, 3.4655]])
tensor([[ 7.4616, 89.7312, 29.8794, 20.4175],
        [ 0.8991, 13.5241, 15.6567,  3.9385],
        [18.2425, 28.7346, 27.8574, 29.1036]])


### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [28]:
# creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9308, 0.6146, 0.7811, 0.4626],
        [0.0518, 0.1819, 0.6073, 0.4585],
        [0.9388, 0.0791, 0.7418, 0.2962]])

In [33]:
some_tensor.size(), some_tensor.shape # both are same

(torch.Size([3, 4]), torch.Size([3, 4]))

In [34]:
# find out details about `some_tensor`
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9308, 0.6146, 0.7811, 0.4626],
        [0.0518, 0.1819, 0.6073, 0.4585],
        [0.9388, 0.0791, 0.7418, 0.2962]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add 10 to all elements
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# multiply 10 to all elements
tensor * 10

tensor([10, 20, 30])

In [39]:
# subtract 10 from all elements
tensor - 10

tensor([-9, -8, -7])

In [52]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor,tensor)
tensor.shape

torch.Size([3])

### Matrix multiplication

Two main ways of performing multiplacation in neural network and deeplearning:

1. Element-wise Multiplication
2. Matrix multiplication (dot product) (`@` symbol)

There are two main rules that performing matrix multiplication needs to satisfy:

1. the **inner dimensions** must match
2. the resulting matrix has the shape of the **outer dimensions**

In [56]:
torch.matmul(torch.rand(3,4),torch.rand(4,8)).shape

torch.Size([3, 8])

In [54]:
torch.matmul(tensor,tensor) # 1*1 + 2*2 + 3*3

tensor(14)

In [48]:
%%time
value = 0
for i in tensor:
  value += i*i
print(value)

tensor(14)
CPU times: user 2.82 ms, sys: 0 ns, total: 2.82 ms
Wall time: 2.62 ms


In [51]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 121 µs, sys: 0 ns, total: 121 µs
Wall time: 126 µs


tensor(14)

### one of the most common errors in deep learning: shape errors

In [58]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul

To fix our tensor shape isseues, we can munipulate the shape of one of our tensors using a `transpose`.
A `transpose` switches the axes or dimensions of a given tensor.

In [67]:
tensor_B.T
torch.mm(tensor_A,tensor_B.T).shape

torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [93]:
# Create a tensor

x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [94]:
# find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [95]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [96]:
# find the mean

# note: the torch.mean() function requires a tensor of float32 datatype to work

print(x.dtype)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

torch.int64


(tensor(46.), tensor(46.))

In [97]:
# find the sum of elements in the tensor
torch.sum(x),x.sum()

(tensor(460), tensor(460))

## finding the positional min and max

In [98]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [99]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [104]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensirs

* reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory ans the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or sideby side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [117]:
x = torch.arange(1., 10.)
print(x, x.shape)
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [119]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [156]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

temp1 = torch.tensor([[1.],[2.],[3.],[4.],[5.],[6.]])
temp2 = torch.tensor([[4.],[5.],[6.],[7.],[8.],[9.]])
dimension = 2
print(f"temp1 = {temp1}\n temp2 = {temp2}")
stk = torch.stack((temp1, temp2),dim = dimension)
print(f"stacked at dim {dimension} = {stk}\n shape of stacked = {stk.shape}\n\n")
vstk = torch.vstack((temp1, temp2))
hstk = torch.hstack((temp1, temp2))
print(f"vertical stack = {vstk}\n horizontal stack = {hstk}\n")

temp1 = tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
 temp2 = tensor([[4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
stacked at dim 2 = tensor([[[1., 4.]],

        [[2., 5.]],

        [[3., 6.]],

        [[4., 7.]],

        [[5., 8.]],

        [[6., 9.]]])
 shape of stacked = torch.Size([6, 1, 2])


vertical stack = tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
 horizontal stack = tensor([[1., 4.],
        [2., 5.],
        [3., 6.],
        [4., 7.],
        [5., 8.],
        [6., 9.]])

