### 1. Documentation reading:
 A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation for `torch.Tensor` and `torch.cuda`

### 2. Create a random tensor with shape (7, 7).

In [19]:
import torch

tensor = torch.rand(7,7)
print(tensor)

tensor([[0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388],
        [0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399],
        [0.4517, 0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893],
        [0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770],
        [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189],
        [0.0655, 0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658],
        [0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
(hint: you may have to transpose the second tensor).

In [20]:
tensor1 = torch.rand(1,7)
tensor2 = torch.rand(1,7)

print(tensor1.shape)
print(tensor2.T.shape)
print(torch.mm(tensor1, tensor2.T))

torch.Size([1, 7])
torch.Size([7, 1])
tensor([[1.6949]])


### 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [21]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# 2nd:
tensor_seed = torch.rand(7,7)
print(tensor_seed)

# 3rd:
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(1,7)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(1,7)

print(f"tensor_A = {tensor_A}\n tensor_B transpose = {tensor_B.T}")
print(torch.matmul(tensor_A, tensor_B.T))


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor_A = tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
 tensor_B transpose = tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])
tensor([[1.5985]])


### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [22]:
!nvidia-smi
print(torch.cuda.is_available())

torch.cuda.manual_seed(1234)

tensor_cuda_random = torch.rand(4,4)

print(tensor_cuda_random)

Mon Apr 29 16:34:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0              29W /  70W |    151MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [23]:
torch.manual_seed(1234)
cpu_tensor1 = torch.rand(2,3)
cpu_tensor2 = torch.rand(2,3)

print(f"cpu_tensor1 device = {cpu_tensor1.device} \t cpu_tensor2 device = {cpu_tensor2.device}")

device = "cuda" if(torch.cuda.is_available()) else "cpu"
gpu_tensor1 = cpu_tensor1.to(device = device)
# gpu_tensor2 = cpu_tensor2.cuda(device = device)
gpu_tensor2 = torch.rand([2,3], device = device)

print(f"gpu_tensor1 device = {gpu_tensor1.device} \t gpu_tensor2 device = {gpu_tensor2.device}")

cpu_tensor1 device = cpu 	 cpu_tensor2 device = cpu
gpu_tensor1 device = cuda:0 	 gpu_tensor2 device = cuda:0


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [24]:
matrix_multiplication = torch.mm(gpu_tensor1, gpu_tensor2.T)
print(matrix_multiplication)

tensor([[0.4733, 0.3815],
        [0.4754, 0.9401]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [25]:
mx = torch.max(matrix_multiplication)
mn = torch.min(matrix_multiplication)
print(f"maximum value in the tensor is {mx}\n minimum value in the tensor is {mn}")

maximum value in the tensor is 0.9400702714920044
 minimum value in the tensor is 0.3814699351787567


### 9. Find the maximum and minimum index values of the output of 7.

In [36]:
mx_idx = torch.argmax(matrix_multiplication)
mn_idx = matrix_multiplication.argmin()

print(f"maximum is at {mx_idx}\n minimum is at {mn_idx}")

maximum is at 3
 minimum is at 1


### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [39]:
torch.manual_seed(7)
temp_tensor = torch.rand(1,1,1,10)
ones_tensor = torch.ones_like(temp_tensor)
print(f"temp_tensor = {temp_tensor} with shape = {temp_tensor.shape}")
print(f"ones-tensor = {ones_tensor} with shape = {ones_tensor.shape}")

squeezed_tensor = torch.squeeze(temp_tensor)
print(f"squeezed version of temp-tensor = {squeezed_tensor} with shape = {squeezed_tensor.shape}")

temp_tensor = tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) with shape = torch.Size([1, 1, 1, 10])
ones-tensor = tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]]]) with shape = torch.Size([1, 1, 1, 10])
squeezed version of temp-tensor = tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) with shape = torch.Size([10])
